{% set name = "pymc-sphinx-theme" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: cbaf6b479f47f47ed840a8ad8e5af0ed32627d41a731d26419b520140e3ce13d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.4,<4
    - pip
  run:
    - python >={{ python_min }}
    - pydata-sphinx-theme >=0.16.0,<0.17,!=0.16.1
    - sphinx >=5

test:
  imports:
    - pymc_sphinx_theme
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A thin sphinx theme to customize pydata-sphinx-theme consistently cross PyMC websites.
  home: https://github.com/pymc-devs/pymc-sphinx-theme
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
    - OriolAbril
